#!/bin/bash

# Functions to call

# script instance limit func
#spawn_check() 
#{
#         running_instances=$(pgrep -fla "$script_name" | grep -v grep | wc -l)
#     if [ "$running_instances" -gt 2 ]; then
#         echo "Another instance of the script is already running. Please try again."
#         exit 1
#     else
#         echo "Starting the script..."
#         if ! pgrep -f "start" > /dev/null; then
#             nohup start > "$log_path" 2>&1 &
#             script_pid=$!
#         fi
#     fi
# }	

# user interaction func
user_interaction() {
	current_dir=$(pwd)

	while true; do
		echo "Enter a command (type 'quit' to exit): "
		read user_command

		if [[ "$user_command" == "quit" ]]; then
			echo "Exiting"
			cleanup
			break
		else
		# cd interpret handler
			if [[ "$user_command" =~ ^cd ]]; then
				new_dir=$(cd "$current_dir"; eval "$user_command"; pwd)
			if [ -d "$new_dir" ]; then
				current_dir="$new_dir"
			else
				cleanup
				break
			fi
			else
				(cd "$current_dir"; eval "$user_command")
			fi
		fi
	done
	}

# force quit cleanup func
cleanup() {
        echo ""
    echo "Performing cleanup tasks..."
        echo ""
        for game_files in /tmp/game/*; do
            filename=$(basename "$game_files")
            if [[ $filename != "start" ]]; then
				rm -rf /tmp/game/
				rm -rf /tmp/exit_con/
				echo "Quitting game - Thanks for playing"
            fi
        done
    if [[ -n $script_pid ]]; then
        kill $script_pid
    fi
}

# Make generic game files
mkdir -p /tmp/exit_con/
mkdir -p /tmp/game/inventory/
touch /tmp/exit_con/exit_condition.log
echo "" > /tmp/exit_con/exit_condition.log
script_name=$(basename "$0")
log_path="/tmp/exit_con/exit_condition.log"

# game menu
menu() {
	clear
	echo "+=================================================+"
	echo "|              Welcome to the game!               |"
	echo "| Please select what level you would like to play |"
	echo "| Level 1 - '1'                                   |"
	echo "| Level 2 - '2'            /| ________________    |"
	echo "| Level 3 - '3'      O|===|* >________________>   |"
	echo "| Level 4 - '4'            \|                     |"
	echo "| Level 5 - '5'                        'q' = Quit |"
	echo "+=================================================+"
	read -p "Input: " user_input
	case $user_input in
		1)
			bash ../levels/level_1
			;;
		2)
#			level_2
			echo "Level incomplete - Check back another time"
			read -p "Press [Enter] to continue"
			menu
			;;
		3)
#			level_3
			echo "Level incomplete - Check back another time"
			read -p "Press [Enter] to continue"
			menu
			;;
		4)
#			level_4
			
			echo "Level incomplete - Check back another time"
			read -p "Press [Enter] to continue"
			menu
			;;
		5)
#			level_5
			echo "Level incomplete - Check back another time"
			read -p "Press [Enter] to continue"
			menu
			;;
		q)
			cleanup
			exit
			;;
		*)
			echo "Invalid input - Press [Enter] to continue"
			read -p ""
			menu
			;;
	esac
}

spawn_check
menu
